# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "Yd1ZHQdhy5iS7q6cBopwwJPgfrWiAhv5pf5+PnUQ70yrRahyk5SIcSmj6IM+zZX93Nr8EqD8W9zah9bA8eZZw8olgo53oAbRkdM4R0NBXxjBOwPEtXxZmfXkmzxZ4LlBrmukoE33LB6V95HnS9fyzfklwAlbBAoPepG5R4e27b7J/I4bPj0T6+jJGT7XAvWiEFJENLW1rMaxQ45bf5z4QGf0eOTgziHAwVxHD58XeReKnuIE6Y0/9jzGJV+wCvlpYmI8pkfMa8sUpH4U6DL6Nx4nCUHVNF+Pf0lYHNEqRBsLUVCLDcA1TZ36r+jb5NanS56DVaXn1BvlaS79DArl2eElXLKKTmWsdRCjFf2OkeiyuZaG2z+MU9b4zbC2i3coXX8sDZwOL+ceHcSRS9FOQsi4S6KFBlksFVPQ4Y8IO6utuV1D648onDyCyuPVIM2Ddku99EN5Fbk92DzQM3tktX+brfmcFgtHMI1eY6O3BEXrVuvGccC4vZsNsJW81zM/9bls9Cc5u2ckdSGe3sr++KsshBSRn2xkHywSo/K3pHxBgGKwe8orrgRN/pQJCpDF0Nb9rOr7ZPC657g61N5hPZgmh/WQCeLuJf2MLYWFNolihYw1A240yOuhEX9V1VCZBQFAWZGv73A+HbODEneVtZzW3g5OPRKxTKd/2vqyRBE="

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
install:
  - pip install git+https://github.com/adblockplus/python-abp
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"

# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - git clone -b gh-pages "https://$GITHUB_TOKEN@github.com/easylist/easylist" output
  - flrender -i easylist=. easylist.template output/easylist.txt
  - flrender -i easylist=. easyprivacy.template output/easyprivacy.txt
  - flrender -i easylist=. fanboy-social.template output/fanboy-social.txt
  - flrender -i easylist=. fanboy-annoyance.template output/fanboy-annoyance.txt  
  - cd output && git add --all . && git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin gh-pages

