# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/customizing-the-build/#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - secure: "RruCqNDHe93UTDCobpNNFBGXX/z45cy4MyuH0eaPVuOgCimMwGYwNxjsv8xK6cWqwsCib3uzdvOyXLPQsRAcV1KmLFg/r1gXEGstgFRX8XCAeGQr+LI/T+cQXwe8pIJFk8jabUH8oNU/tRyWiCEVpFV3+wokq6VQItDbykSBVJ3Y1iXxNDYNJ/7k8VgjFxXOn9BSwstG20RA6DGQbdldlA7f4pv7qY5vQvh9J7yLhgpICdFwWLTHpRn4wOJPriUYSPDo4avPEYp6BOvAh6vp7dTbzAlwke8c7NYEuGX2e1Yd0fOqxMqErX1k0Bt5M/s00sP6XtbWvd75I+V0Gy/SgBsJif/YN2a4okx2WvVgriCd8TQj7AW8WaR0ZRKWWPKGGbTtxJEJzLO9Ici9So6yyXNOW/d2WJlRCdRtnBeM1SBQUDWnNkQcYw7MMsHPD7wHsKqw/zK5txmQ2krvmwv0k8nCfavOVHsWf1RG9LTLwLNe4vQXz/B/8Ezneprc8w78mK/CJueNVr7WTb6nT3Cv7dazPv+eGRO/DcZPKynUZ4b2OqMtq+5FXNckrxwKFEIZcNp9IaSXJSW35gPtSw62fIXniPyU1jA0Eq5FWOuLYbkxaJy1GQ0xwDRTWAU7qYwu94fLcbFuoIQy6na34g6zeK1OAV14Xw9MRxEBfJoAuLw="

# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
install:
  - pip install git+https://github.com/adblockplus/python-abp
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"

# https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step
script:
  - git clone -b gh-pages "https://$GITHUB_TOKEN@github.com/easylist/easylist" output
  - flrender -i easylist=. easylist.template output/easylist.txt
  - flrender -i easylist=. easyprivacy.template output/easyprivacy.txt
  - flrender -i easylist=. fanboy-social.template output/fanboy-social.txt
  - flrender -i easylist=. fanboy-annoyance.template output/fanboy-annoyance.txt  
  - cd output && git add --all . && git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin gh-pages

