name: Filters Lists Lint

on:
  push:
    branches:
      - master
    paths:
      - "**/*.txt"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.txt"

jobs:
  fop:
    name: Run FOP.py to check ordering
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v4
      - name: Run FOP.py
        run: true || echo "" | python3 FOP.py
        shell: bash
      - name: Run git diff
        run: |
          ! git diff --stat | grep -E "[A-Za-z0-9-]+\.txt"
        shell: bash
  aglint:
    name: Run AGLint
    runs-on: ubuntu-latest
    steps: 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Check out to repository
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm i
        shell: bash
      - name: Run AGLint
        run: npm run aglint
        shell: bash